AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'db/schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/channels/application_cable/**'
    - 'bin/**'
    - 'config/**'
    - 'db/**'
    - 'app/controllers/users/viewing_party_controller.rb'

Style/StringLiterals:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false